# Generated by Django 4.2.11 on 2024-04-05 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_yoga', '0002_alter_timetableentry_id_sessionbooking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessionbooking',
            old_name='timetable_entry',
            new_name='session',
        ),
    ]
