# Generated by Django 4.2.11 on 2024-04-05 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_yoga', '0003_rename_timetable_entry_sessionbooking_session'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessionbooking',
            old_name='session',
            new_name='timetable_entry',
        ),
        migrations.AddField(
            model_name='sessionbooking',
            name='additional_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionbooking',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='sessionbooking',
            name='full_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sessionbooking',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='sessionbooking',
            name='booking_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
